# Generated by Django 3.2.5 on 2021-12-26 06:58

import builtins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('a', '学生'), ('b', '老师'), ('c', '管理员')], default='a', max_length=1, verbose_name='身份')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='学号/工号')),
                ('name', models.CharField(max_length=5, verbose_name='姓名')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('brief', models.TextField(null=True, verbose_name='简介')),
            ],
            options={
                'verbose_name': '班级',
                'verbose_name_plural': '班级',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('deptId', models.IntegerField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=10, null=True, verbose_name='院系名')),
                ('dept_credit', models.IntegerField(default=150, verbose_name='所需学分')),
            ],
            options={
                'verbose_name': '院系',
                'verbose_name_plural': '院系',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='attrs.account')),
            ],
            options={
                'verbose_name': '管理员',
                'verbose_name_plural': '管理员',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='attrs.account')),
                ('teacher_age', models.IntegerField(default=0)),
                ('teacher_email', models.CharField(max_length=30, null=True, verbose_name='邮箱')),
                ('telephone', models.CharField(max_length=11, null=True, unique=True, verbose_name='联系电话')),
                ('teacher_dept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attrs.department', verbose_name='学院号')),
            ],
            options={
                'verbose_name': '教师',
                'verbose_name_plural': '教师',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='attrs.account')),
                ('student_inyear', models.CharField(max_length=5)),
                ('student_age', models.IntegerField(default=0)),
                ('student_home', models.CharField(max_length=15)),
                ('student_credit', models.IntegerField(default=0, verbose_name='已修学分')),
                ('student_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attrs.class', verbose_name='班级号')),
                ('student_dept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attrs.department', verbose_name='学院号')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
                'ordering': [builtins.id],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('code', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True, verbose_name='课程码')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='课程名称')),
                ('type', models.CharField(choices=[('a', '必修'), ('b', '选修'), ('c', '限修'), ('d', '任修')], default='a', max_length=1, verbose_name='课程类别')),
                ('ident', models.CharField(max_length=10)),
                ('credit', models.IntegerField(verbose_name='学分')),
                ('pred', models.ForeignKey(max_length=15, null=True, on_delete=django.db.models.deletion.CASCADE, to='attrs.course', verbose_name='学院号')),
                ('courseStudent', models.ManyToManyField(to='attrs.Student', verbose_name='课程学生')),
                ('courseTeacher', models.ManyToManyField(to='attrs.Teacher', verbose_name='课程教师')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
            },
        ),
    ]
