# Generated by Django 3.2.5 on 2021-12-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attrs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='dept_leader',
            field=models.CharField(max_length=10, null=True, verbose_name='系主任'),
        ),
    ]
