# Generated by Django 3.2.5 on 2021-12-27 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attrs', '0002_department_dept_leader'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': '账户', 'verbose_name_plural': '账户'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '学生', 'verbose_name_plural': '学生'},
        ),
        migrations.RenameField(
            model_name='department',
            old_name='deptId',
            new_name='dept_id',
        ),
    ]
