# Generated by Django 3.2.5 on 2021-12-28 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attrs', '0003_auto_20211227_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_home',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_inyear',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
