# Generated by Django 3.2.5 on 2021-12-28 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attrs', '0005_remove_course_ident'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startweek', models.IntegerField(verbose_name='开始周数')),
                ('duringweek', models.IntegerField(verbose_name='持续周数')),
                ('weekday', models.IntegerField(verbose_name='星期')),
                ('startsection', models.IntegerField(verbose_name='开始节数')),
                ('durinsection', models.IntegerField(verbose_name='持续节数')),
            ],
            options={
                'verbose_name': '课程时间',
                'verbose_name_plural': '课程时间',
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='pred',
            field=models.ForeignKey(max_length=15, null=True, on_delete=django.db.models.deletion.CASCADE, to='attrs.course', verbose_name='先修课'),
        ),
        migrations.AddField(
            model_name='course',
            name='time',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='attrs.coursetime'),
        ),
    ]
