# Generated by Django 3.2.5 on 2021-12-28 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attrs', '0007_auto_20211228_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attrs.department', verbose_name='开课学院'),
        ),
    ]
