# Generated by Django 3.2.5 on 2021-12-29 00:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('attrs', '0008_alter_course_dept'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime(2021, 12, 29, 0, 35, 46, 32755, tzinfo=utc), verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '通知信息',
                'verbose_name_plural': '通知信息',
            },
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_email',
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, to='attrs.Course', verbose_name='已选课程'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='courses',
            field=models.ManyToManyField(blank=True, to='attrs.Course', verbose_name='开设课程'),
        ),
        migrations.CreateModel(
            name='OpenTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=20)),
                ('course_time', models.CharField(max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attrs.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attrs.teacher')),
            ],
            options={
                'db_table': 'OpenTable',
            },
        ),
        migrations.CreateModel(
            name='ScoreTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('open', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attrs.opentable')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attrs.student')),
            ],
            options={
                'db_table': 'ScoreTable',
                'unique_together': {('student', 'open')},
            },
        ),
    ]
