# Generated by Django 3.2.5 on 2021-12-29 00:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('attrs', '0009_auto_20211229_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attrs.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attrs.student')),
            ],
            options={
                'verbose_name': '选课表SC',
                'verbose_name_plural': '选课表SC',
            },
        ),
        migrations.AlterUniqueTogether(
            name='scoretable',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='scoretable',
            name='open',
        ),
        migrations.RemoveField(
            model_name='scoretable',
            name='student',
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 29, 0, 51, 31, 251362, tzinfo=utc), verbose_name='发布时间'),
        ),
        migrations.DeleteModel(
            name='OpenTable',
        ),
        migrations.DeleteModel(
            name='ScoreTable',
        ),
    ]
