# Generated by Django 3.2.5 on 2021-12-29 04:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('attrs', '0010_auto_20211229_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='courseStudent',
        ),
        migrations.RemoveField(
            model_name='course',
            name='courseTeacher',
        ),
        migrations.RemoveField(
            model_name='score',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='semi',
            field=models.IntegerField(default=2021, verbose_name='课程时间'),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='score',
            name='student',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='attrs.student'),
        ),
        migrations.CreateModel(
            name='OpenCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(blank=True, max_length=20)),
                ('course_time', models.CharField(max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attrs.course', verbose_name='m')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attrs.teacher')),
            ],
            options={
                'verbose_name': '开课表',
                'verbose_name_plural': '开课表',
            },
        ),
        migrations.AddField(
            model_name='score',
            name='open',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, to='attrs.opencourse'),
            preserve_default=False,
        ),
    ]
