# Generated by Django 3.2.5 on 2021-12-29 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attrs', '0011_auto_20211229_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opencourse',
            name='course_time',
        ),
        migrations.RemoveField(
            model_name='opencourse',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='courses',
        ),
        migrations.AlterField(
            model_name='course',
            name='semi',
            field=models.IntegerField(default=2021, verbose_name='课程学年'),
        ),
    ]
