# Generated by Django 3.2.5 on 2021-12-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attrs', '0014_auto_20211229_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='building',
            field=models.CharField(max_length=10, verbose_name='楼号'),
        ),
    ]
