# Generated by Django 3.2.5 on 2021-12-29 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attrs', '0015_alter_place_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attrs.place', verbose_name='课程地点'),
        ),
    ]
