# Generated by Django 3.2.5 on 2021-12-29 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attrs', '0016_course_place'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['code'], 'verbose_name': '课程', 'verbose_name_plural': '课程'},
        ),
        migrations.RenameField(
            model_name='coursetime',
            old_name='durinsection',
            new_name='duringsection',
        ),
    ]
