# Generated by Django 3.2.5 on 2021-12-30 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attrs', '0017_auto_20211229_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='eval',
            field=models.BooleanField(default=False, verbose_name='是否评价'),
        ),
        migrations.AddField(
            model_name='score',
            name='mark',
            field=models.FloatField(default=0, verbose_name='评教分数'),
        ),
        migrations.AddField(
            model_name='score',
            name='record',
            field=models.BooleanField(default=False, verbose_name='录入状态'),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.FloatField(default=0, verbose_name='最终成绩'),
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='attrs.course', verbose_name='考试课程')),
                ('time', models.DateTimeField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attrs.place', verbose_name='考试地点')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attrs.teacher', verbose_name='监考教师')),
            ],
            options={
                'verbose_name': '考试表',
                'verbose_name_plural': '考试表',
            },
        ),
    ]
