# Generated by Django 3.2.5 on 2021-12-30 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attrs', '0018_auto_20211230_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_credit',
            new_name='credit',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_dept',
            new_name='dept',
        ),
        migrations.RemoveField(
            model_name='score',
            name='record',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_age',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_home',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_inyear',
        ),
        migrations.AddField(
            model_name='exam',
            name='id',
            field=models.BigAutoField(auto_created=True, default=300, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opencourse',
            name='record',
            field=models.BooleanField(default=False, verbose_name='录入状态'),
        ),
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=18, verbose_name='年龄'),
        ),
        migrations.AddField(
            model_name='student',
            name='home',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='家乡'),
        ),
        migrations.AddField(
            model_name='student',
            name='inyear',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='入学年份'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attrs.course', verbose_name='考试课程'),
        ),
    ]
