# Generated by Django 3.2.5 on 2022-01-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attrs', '0019_auto_20211230_2011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['no'], 'verbose_name': '院系', 'verbose_name_plural': '院系'},
        ),
        migrations.RenameField(
            model_name='department',
            old_name='dept_credit',
            new_name='fullcredit',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='dept_leader',
            new_name='leader',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='dept_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='dept_id',
            new_name='no',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher_age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher_dept',
            new_name='dept',
        ),
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
        migrations.AlterField(
            model_name='student',
            name='inyear',
            field=models.CharField(default=2021, max_length=5, verbose_name='入学年份'),
        ),
    ]
