# Generated by Django 3.2.5 on 2022-01-02 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attrs', '0020_auto_20220101_1608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opencourse',
            options={'ordering': ['course__code'], 'verbose_name': '开课表', 'verbose_name_plural': '开课表'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['building'], 'verbose_name': '地点', 'verbose_name_plural': '地点'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['id__code'], 'verbose_name': '学生', 'verbose_name_plural': '学生'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['id__code'], 'verbose_name': '教师', 'verbose_name_plural': '教师'},
        ),
    ]
